services:
  snaptix-user-accounts-db:
    image: postgres:17.9
    container_name: snaptix-user-accounts-db
    hostname: snaptix-user-accounts-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-accounts
    ports:
      - '10000:5432'
    volumes:
      - snaptix-user-accounts-db:/var/lib/postgresql/data
    networks:
      - snaptix-backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user-accounts" ]
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  snaptix-user-accounts-db:
networks:
  snaptix-backend-network:
    name: snaptix-backend-network
