services:
  snaptix-user-accounts-db:
    image: postgres:17.9
    container_name: snaptix-user-accounts-db
    hostname: snaptix-user-accounts-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-accounts
    ports:
      - '10000:5432'
    volumes:
      - snaptix-user-accounts-db:/var/lib/postgresql/data
    networks:
      - snaptix-backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user-accounts" ]
      interval: 2s
      timeout: 5s
      retries: 30

  snaptix-rabbitmq:
    image: rabbitmq:4-management
    container_name: snaptix-rabbitmq
    hostname: snaptix-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 10s
      retries: 30


volumes:
  snaptix-user-accounts-db:
networks:
  snaptix-backend-network:
    name: snaptix-backend-network
