services:
  snaptix-postgres:
    image: postgres:17.9
    container_name: snaptix-postgres
    hostname: snaptix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '10000:5432'
    volumes:
      - snaptix-postgres:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - snaptix-backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 30

  snaptix-rabbitmq:
    image: rabbitmq:4-management
    container_name: snaptix-rabbitmq
    hostname: snaptix-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 10s
      retries: 30

  snaptix-maildev:
    image: maildev/maildev:2.2.1
    container_name: snaptix-maildev
    hostname: snaptix-maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:1080/ > /dev/null 2>&1" ]
      interval: 2s
      timeout: 5s
      retries: 30

volumes:
  snaptix-postgres:
networks:
  snaptix-backend-network:
    name: snaptix-backend-network
