apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true      # опционально, но хорошая практика
            runAsUser: 1000         # опционально
          ports:
            - containerPort: PORT_CONTAINER
          env:
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: CORS_ALLOWED_ORIGINS
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: RECAPTCHA_SECRET
            - name: IS_SWAGGER_ENABLED
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: IS_SWAGGER_ENABLED
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: ACCESS_TOKEN_SECRET
            - name: MICROSERVICE_USER_ACCOUNTS_HOST
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: MICROSERVICE_USER_ACCOUNTS_HOST
            - name: MICROSERVICE_USER_ACCOUNTS_PORT
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: MICROSERVICE_USER_ACCOUNTS_PORT
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: REFRESH_TOKEN_SECRET
            - name: MICROSERVICE_POSTS_HOST
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: MICROSERVICE_POSTS_HOST
            - name: MICROSERVICE_POSTS_PORT
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: MICROSERVICE_POSTS_PORT
            - name: MICROSERVICE_FILES_PORT
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: MICROSERVICE_FILES_PORT
            - name: MICROSERVICE_FILES_HOST
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: MICROSERVICE_FILES_HOST
            - name: FILES_STORAGE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: FILES_STORAGE_BASE_URL
            - name: MICROSERVICE_GEO_HOST
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: MICROSERVICE_GEO_HOST
            - name: MICROSERVICE_GEO_PORT
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: MICROSERVICE_GEO_PORT
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: NODE_ENV
